[package]
org = "ballerinax"
name = "aws.redshift"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["Data Warehouse", "Columnar Storage", "Cost/Paid", "vendor/aws"]
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.redshift"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "aws.redshift-native"
version = "@project.version@"
path = "../native/build/libs/aws.redshift-native-@project.version@.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "@sql.native.version@"
path = "./lib/sql-native-@sql.native.version@.jar"
