[package]
org = "ballerinax"
name = "aws.redshift"
version = "1.0.1"
authors = ["Ballerina"]
keywords = ["Data Warehouse", "Columnar Storage", "Cost/Paid", "vendor/aws"]
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.redshift"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "aws.redshift-native"
version = "1.0.1-SNAPSHOT"
path = "../native/build/libs/aws.redshift-native-1.0.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.11.0"
path = "./lib/sql-native-1.11.0.jar"
